<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookLeft.Application\BookRight.Application.csproj" />
    <ProjectReference Include="..\BookLeft.Domain\BookRight.Domain.csproj" />
    <ProjectReference Include="..\BookLeft.Facade\BookRight.Facade.csproj" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
  </ItemGroup>

</Project>
