<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\CustomerDto\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Dtos\CustomerDto\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Dtos\CustomerDto\**" />
    <None Remove="Services\**" />
  </ItemGroup>

</Project>
